//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicEightBallServiceClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://MyCompany.com", ConfigurationName="ServiceReference1.IEightBall")]
    public interface IEightBall {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MyCompany.com/IEightBall/ObtainAnswerToQwestion", ReplyAction="http://MyCompany.com/IEightBall/ObtainAnswerToQwestionResponse")]
        string ObtainAnswerToQwestion(string userQuestion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MyCompany.com/IEightBall/ObtainAnswerToQwestion", ReplyAction="http://MyCompany.com/IEightBall/ObtainAnswerToQwestionResponse")]
        System.Threading.Tasks.Task<string> ObtainAnswerToQwestionAsync(string userQuestion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEightBallChannel : MagicEightBallServiceClient.ServiceReference1.IEightBall, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EightBallClient : System.ServiceModel.ClientBase<MagicEightBallServiceClient.ServiceReference1.IEightBall>, MagicEightBallServiceClient.ServiceReference1.IEightBall {
        
        public EightBallClient() {
        }
        
        public EightBallClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EightBallClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EightBallClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EightBallClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ObtainAnswerToQwestion(string userQuestion) {
            return base.Channel.ObtainAnswerToQwestion(userQuestion);
        }
        
        public System.Threading.Tasks.Task<string> ObtainAnswerToQwestionAsync(string userQuestion) {
            return base.Channel.ObtainAnswerToQwestionAsync(userQuestion);
        }
    }
}
