//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpTestConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public override string ToString()
        {
            return string.Format("{0} is as {1}   {2}  with ID {3}", this.CarNickName ?? "**No Name**", this.Color, this.Make, this.CarID);
        }

        partial void OnCarNickNameChanging(global::System.String value)
        {
            Console.WriteLine("\t-> Changing name to: {0}", value);
        }

        partial void OnCarNickNameChanged()
        {
            Console.WriteLine("\t Name of car has been changed!");
        }
        //public int CarID { get; set; }
        //public string Make { get; set; }
        //public string Color { get; set; }
        //public string CarNickName { get; set; }
    }
}
